// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhukvyjukajzrcqisycs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1odWt2eWp1a2FqenJjcWlzeWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzA3MTgsImV4cCI6MjA3MDA0NjcxOH0.Tvp7AZUB00ZL_4yUJkgJ6SffJ4nQEeeyyv8wD2v1SEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});